### ISSUE TITLE
DVR Plugin is broken

### ISSUE THREAD

**Issue by ajvpot** [mmcgill/mc3p#8]
alex@box:~/mc3p/mmcgill-mc3p-62e17c1/mc3p$ python proxy.py -p 25565 --plugin 'plugin.dvr' server.com
ERROR:plugins:Plugin 'plugin.dvr' does not contain a subclass of MC3Plugin

alex@box:~/mc3p/mmcgill-mc3p-62e17c1/mc3p$ ls
**init**.py  messages.py   parsing.py   plugin      plugins.pyc  util.py
blocks.py    messages.pyc  parsing.pyc  plugins.py  proxy.py     util.pyc

When I attempt to run the DVR plugin, it complains about the above error. I can tell that it is attempting to load the correct file, because 'dvr' and 'mc3p.plugin.dvr' say file not found.

**Comment by mmcgill** [comment]
Hi ajvpot,

I think the problem is poor documentation. Right now, the only docs on the DVR plugin are the header comment in mc3p/plugin/dvr.py, and it's out of date :( I'll write a wiki page explaining how to use DVR. In the mean time, this might get you started:

DVR is a tool for testing plugins (and mc3p itself). When run as a plugin, it captures messages exchanged between a client and server, and saves them to a file. When run as a stand-alone program, it acts as both the client and server to replay the exchanged messages through mc3p, for testing.

To capture all client and server packets, run it like this:

`alex@box:~/mc3p/mmcgill-mc3p-62e17c1$ python -m mc3p.proxy --plugin 'mc3p.plugin.dvr(-s * -c * capture01)' serverserver.com`

Note that you need to run mc3p as a module (i.e. with the -m flag), and from the parent directory of mc3p/, as shown above.

After running that command, connect your Minecraft client through the proxy and play around for a few seconds, then quit. Shut down mc3p. You should have two new files, capture01.cli and capture01.srv.

To replay those packets, first start mc3p so as to forward to your _local machine_:

`$ python -m mc3p.proxy localhost`

Then, in another terminal, run DVR like so:

`$ python -m mc3p.plugin.dvr capture01`

You won't see much of anything happen, but DVR is replaying all the captured messages through the proxy.
